name: Build Docker Image

on:
  push:
    branches:
      - main
      - dev-nextjs
  pull_request:
    branches:
      - main
      - dev-nextjs
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build --progress=plain -t "$REGISTRY_URL/main-website-next" .

    - name: Log in to Docker registry
      run: echo "$REGISTRY_PASSWORD" | docker login "$REGISTRY_URL" -u "$REGISTRY_USERNAME" --password-stdin

    - name: Push Docker image
      run: docker push "$REGISTRY_URL/main-website-next"
